apiVersion: v1
kind: ReplicaSet
metadata: 
  name: BERT-replicaset
  labels:
    app: BERT
    tier: backend
spec:
  template:
    metadata:
      name: BERT-pod
      labels:
        app: BERT
        type: backend
    spec:
      containers:
      - name: BERT-container
        image: bert:latest
  replicas: 3
  selector: 
    matchLabels:
      type: backend